### ISSUE TITLE
Air alarms not working

### ISSUE THREAD

**Issue by mabmoro** [PolarisSS13/Polaris#8127]
#### Brief description of the issue

Air alarms not reading atmos or connected devices. Errors when clicking alarm threshold.

#### What you expected to happen
Adjust atmos

#### What actually happened
TypeError: Unable to get property 'map' of undefined or null reference
   at V (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:35:65607)
   at Anonymous function (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:70544)
   at Anonymous function (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:70514)
   at Se (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:70492)
   at Anonymous function (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:72197)
   at Pe (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:72066)
   at Oe (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:74264)
   at Anonymous function (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:72724)
   at Pe (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:72263)
   at Anonymous function (http://127.0.0.1:59615/tmp25616/tgui.bundle.js:31:75020)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; wbxapp 1.0.0; Zoom 3.6.0)

#### Steps to reproduce
Click on atmos alarm, click any button and either get nothing or the above error.

#### Additional info:
 - **Server Revision**: master - 2021-05-29 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Further context: there's a runtime at `code/game/obj/machinery/air_alarm.dm:568: ilist index out of bounds`
on
`data["scrubbers"][data["scrubbers"].len]["filters"] += list(list("name" = "Oxygen",			"command" = "o2_scrub",	"val" = info["filter_o2"]))`
data["scrubbers"][data["scrubbers"].len is messy, but correct, that index has been preinitialized to a list.
["filters"] is also correct, that's a valid list entry
The only index in the list definition is `info["filter_o2"]` but as far as I can tell that's also correct?

So not really sure why this is broken, but the runtime is most likely causing the tgui failure.
